# Generated by Django 4.0.1 on 2022-04-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='status',
            field=models.CharField(blank=True, default='no', max_length=200),
        ),
    ]
